name: Run tests for Task service
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
      - name: Get Code
        uses: actions/checkout@v5
    # Setup .Net SDK 9
      - name: Setup .Net SDK 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packges
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget
    # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore SmartTask360.slnx

    # Build solution
      - name: Build solution
        run: dotnet build SmartTask360.slnx --configuration Release --no-restore

    # Run tests
      - name: Run tests
        run: dotnet test